apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: droplet-market-{{.UniqueId}}-deployment
spec:
  replicas: 1
  serviceName: droplet-market-{{.UniqueId}}-svc
  selector:
    matchLabels:
      app: droplet-market-{{.UniqueId}}-pod
  template:
    metadata:
      labels:
        app: droplet-market-{{.UniqueId}}-pod
    spec:
      containers:
        - name: droplet-market-{{.UniqueId}}
          image: "{{if gt (len .Registry) 0}}{{.Registry}}/{{end}}filvenus/droplet:{{.CodeVersion}}"
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - mkdir -p /root/.droplet/ && rm -rf /root/.droplet/config.toml && cp /root/config.tmp /root/.droplet/config.toml && /app/droplet run;
          ports:
            - containerPort: 41235
              protocol: TCP
            - containerPort: 58418
              protocol: TCP
          volumeMounts:
            - mountPath: /root
              name: droplet-market-pvc
{{ range $index, $value := .PieceStores }}
            - mountPath: /piece/{{$value}}
              name: {{$value}}
{{ end }}
            - name: marketcfg
              mountPath: "/root/config.tmp"
              subPath: "config.toml"
            - mountPath: /shared-dir
              name: shared-dir-v
              subPath: {{.NameSpace}}
      volumes:
        - name: marketcfg
          configMap:
            name: droplet-market-cfg-{{.UniqueId}}
            items:
              - key: config.toml
                path: config.toml
        - name: shared-dir-v
          persistentVolumeClaim:
            claimName: shared-dir
{{ range $index, $value := .PieceStores }}
        - name: {{$value}}
          persistentVolumeClaim:
            claimName: {{$value}}
{{ end }}

  volumeClaimTemplates:
    - metadata:
        name: droplet-market-pvc # name+podname
        labels:
          app: droplet-market-{{.UniqueId}}-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 1Gi