apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: venus-wallet-{{.UniqueId}}
spec:
  replicas: 1
  serviceName: venus-wallet-{{.UniqueId}}-svc
  selector:
    matchLabels:
      app: venus-wallet-{{.UniqueId}}-pod
  template:
    metadata:
      labels:
        app: venus-wallet-{{.UniqueId}}-pod
    spec:
      containers:
        - name: venus-wallet-{{.UniqueId}}
          image: "{{if gt (len .Registry) 0}}{{.Registry}}/{{end}}filvenus/venus-wallet:{{.CodeVersion}}"
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - mkdir -p /root/.venus_wallet && cp /root/config.tmp /root/.venus_wallet/config.toml && /app/venus-wallet run;
          ports:
            - containerPort: 5678
              protocol: TCP
          volumeMounts:
            - mountPath: /root
              name: venus-wallet-pvc
            - name: venus-wallet-cfg
              mountPath: "/root/config.tmp"
              subPath: "config.toml"
      volumes:
        - name: venus-wallet-cfg
          configMap:
            name: venus-wallet-cfg-{{.UniqueId}}
            items:
              - key: config.toml
                path: config.toml
  volumeClaimTemplates:
    - metadata:
        name: venus-wallet-pvc # name+podname
        labels:
          app: venus-wallet-{{.UniqueId}}-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 100Mi